### ISSUE TITLE
Support ENV vars for missing Wordpress configurations

### ISSUE THREAD

**Issue by prydonius** [bitnami/bitnami-docker-wordpress#24]
The chart for this image (https://github.com/bitnami/charts/blob/master/wordpress/templates/deployment.yaml#L43) is setting some ENV vars that aren't currently implemented by this image. Looks like those parameters are supported by the underlying nami module, so we just need to map the ENV vars to those options.

- WORDPRESS_FULLNAME
- WORDPRESS_LASTNAME
- WORDPRESS_BLOGNAME
- SMTP_HOST
- SMTP_PORT
- SMTP_USER
- SMTP_PASSWORD

**Comment by chipironcin** [comment]
Implemented in PR #25 :)

**Comment by chipironcin** [comment]
Pull request merged, could someone confirm if this issue, along with https://github.com/bitnami/charts/ , have been fixed?

**Comment by sameersbn** [comment]
I can confirm that this issue has been resolved :+1:

**Comment by sameersbn** [comment]
I could not get the SMTP options to work, I set the following 

```
- SMTP_HOST=smtp.example.com
- SMTP_PORT=587
- SMTP_USER=notifications@example.com
- SMTP_PASSWORD=secretpassword
- SMTP_USERNAME=noreply@example.com
- SMTP_PROTOCOL=tls
```

Here's the trace.

```application_1  | php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php /tmp/1472830076212.118,bobloblaw,passw0rd,bobloblaw@thelawofficesofbobloblaw.com,Bob LobLaw's Law Blog
application_1  | php     TRACE [runProgram] Executing internal command: /opt/bitnami/php/bin/php ["/tmp/1472830076212.118","bobloblaw","passw0rd","bobloblaw@thelawofficesofbobloblaw.com","Bob LobLaw's Law Blog"]
application_1  | php     TRACE [runProgram] RESULT: {"code":0,"stderr":"","stdout":"exception 'phpmailerException' with message 'Invalid address: wordpress@' in /opt/bitnami/wordpress/wp-includes/class-phpmailer.php:946\nStack trace:\n#0 /opt/bitnami/wordpress/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@', 'WordPress')\n#1 /opt/bitnami/wordpress/wp-admin/includes/upgrade.php(392): wp_mail('bobloblaw@thela...', 'New WordPress S...', 'Your new WordPr...')\n#2 /opt/bitnami/wordpress/wp-admin/includes/upgrade.php(95): wp_new_blog_notification('Bob LobLaw's La...', 'http:', 1, 'The password yo...')\n#3 /tmp/1472830076212.118(23): wp_install('Bob LobLaw's La...', 'bobloblaw', 'bobloblaw@thela...', 1, '', 'passw0rd')\n#4 {main}"}
application_1  | wordpre TRACE [delete] File normalization: /tmp/1472830076212.118 -> /tmp/1472830076212.118
application_1  | wordpre TRACE [puts] File normalization: /opt/bitnami/wordpress/wp-config.php -> /opt/bitnami/wordpress/wp-config.php
application_1  | Error executing 'postInstallation': You should specify username, password, host, port for SMTP configuration
application_1  | nami    TRACE Error: Error executing 'postInstallation': You should specify username, password, host, port for SMTP configuration
application_1  |     at Object.$app.helpers.configureSMTP (/root/.nami/components/com.bitnami.wordpress/helpers.js:115:11)
application_1  |     at Component.$app.postInstallation (/root/.nami/components/com.bitnami.wordpress/main.js:53:18)
application_1  |     at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
application_1  |     at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
application_1  |     at arrayEach (/opt/bitnami/nami/node_modules/lodash/index.js:1289:13)
application_1  |     at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:3345:13)
application_1  |     at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
application_1  |     at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
application_1  |     at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:311:24)
application_1  |     at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:518:30)
```

**Comment by chipironcin** [comment]
Lemme check...

**Comment by chipironcin** [comment]
WIP
https://github.com/bitnami/bitnami-docker-wordpress/pull/33

**Comment by prydonius** [comment]
@sameersbn #33 has been merged, can you confirm the issue is resolved?

**Comment by prydonius** [comment]
Closing this since #30 is open
